/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package net.mcreator.coolmodthatsactuallycool;

import net.minecraftforge.fml.ModList;

import java.util.function.Supplier;
import java.util.function.Function;
import java.util.function.BiConsumer;
import java.util.Set;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class CoolModThatsActuallyCoolModElements {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<Biome>> biomes = new ArrayList<>();
	public final List<Supplier<EntityType<?>>> entities = new ArrayList<>();
	public final List<Supplier<Enchantment>> enchantments = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();
	public CoolModThatsActuallyCoolModElements() {
		sounds.put(new ResourceLocation("cool_mod_thats_actually_cool", "program1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("cool_mod_thats_actually_cool", "program1")));
		sounds.put(new ResourceLocation("cool_mod_thats_actually_cool", "item.blotemeat.sizzle"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("cool_mod_thats_actually_cool", "item.blotemeat.sizzle")));
		sounds.put(new ResourceLocation("cool_mod_thats_actually_cool", "fortress_death"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("cool_mod_thats_actually_cool", "fortress_death")));
		sounds.put(new ResourceLocation("cool_mod_thats_actually_cool", "mob.sandsnail.ambient"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("cool_mod_thats_actually_cool", "mob.sandsnail.ambient")));
		sounds.put(new ResourceLocation("cool_mod_thats_actually_cool", "mob.hamster.hurt"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("cool_mod_thats_actually_cool", "mob.hamster.hurt")));
		sounds.put(new ResourceLocation("cool_mod_thats_actually_cool", "mob.hamster.death"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("cool_mod_thats_actually_cool", "mob.hamster.death")));
		sounds.put(new ResourceLocation("cool_mod_thats_actually_cool", "block.s-portal.enter"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("cool_mod_thats_actually_cool", "block.s-portal.enter")));
		sounds.put(new ResourceLocation("cool_mod_thats_actually_cool", "mob.soulzombie.ambient"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("cool_mod_thats_actually_cool", "mob.soulzombie.ambient")));
		try {
			ModFileScanData modFileInfo = ModList.get().getModFileById("cool_mod_thats_actually_cool").getFile().getScanResult();
			Set<ModFileScanData.AnnotationData> annotations = modFileInfo.getAnnotations();
			for (ModFileScanData.AnnotationData annotationData : annotations) {
				if (annotationData.getAnnotationType().getClassName().equals(ModElement.Tag.class.getName())) {
					Class<?> clazz = Class.forName(annotationData.getClassType().getClassName());
					if (clazz.getSuperclass() == CoolModThatsActuallyCoolModElements.ModElement.class)
						elements.add((CoolModThatsActuallyCoolModElements.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(CoolModThatsActuallyCoolModElements.ModElement::initElements);
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}
	private int messageID = 0;
	public <T> void addNetworkMessage(Class<T> messageType, BiConsumer<T, PacketBuffer> encoder, Function<PacketBuffer, T> decoder,
			BiConsumer<T, Supplier<NetworkEvent.Context>> messageConsumer) {
		CoolModThatsActuallyCoolMod.PACKET_HANDLER.registerMessage(messageID, messageType, encoder, decoder, messageConsumer);
		messageID++;
	}

	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<Biome>> getBiomes() {
		return biomes;
	}

	public List<Supplier<EntityType<?>>> getEntities() {
		return entities;
	}

	public List<Supplier<Enchantment>> getEnchantments() {
		return enchantments;
	}
	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}
		protected final CoolModThatsActuallyCoolModElements elements;
		protected final int sortid;
		public ModElement(CoolModThatsActuallyCoolModElements elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLCommonSetupEvent event) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		@OnlyIn(Dist.CLIENT)
		public void clientLoad(FMLClientSetupEvent event) {
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
