modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="mod"
version="4.1.3"
displayName="Cool Mod that's Actually Cool"
credits="Used some modified Minecraft textures, made with MCreator"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Happymonkey, CactusHamster, Dangerkitty7, ModmakerXtreme"
description='''
A collaboration mod to practice modding skills
'''

[[dependencies.mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




